<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MaiziWPF.Core\MaiziWPF.Core.csproj" />
    <ProjectReference Include="..\MaiziWPF.Services.Application.Contracts\MaiziWPF.Services.Application.Contracts.csproj" />
    <ProjectReference Include="..\MaiziWPF.Services.Domain\MaiziWPF.Services.Domain.csproj" />
  </ItemGroup>
</Project>