<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MaiziWPF.Services.Application.Contracts\MaiziWPF.Services.Application.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\ExpanderMenuControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>