<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Core" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaiziWPF.Common\MaiziWPF.Common.csproj" />
    <ProjectReference Include="..\MaiziWPF.Services.Application.Contracts\MaiziWPF.Services.Application.Contracts.csproj" />
    <ProjectReference Include="..\MaiziWPF.Services.Domain\MaiziWPF.Services.Domain.csproj" />
  </ItemGroup>

</Project>
